### ISSUE TITLE
Upgrading to 1.5.x

### ISSUE THREAD

**Issue by Alir3z4** [django-nonrel/django#2]
Hi,
I've forked the repo to upgrading it to 1.5.x, But there's a **nonrel-1.5-beta** branch that I've not tested it yet.

I would like to know if there's any guide, tips or any other kind of todo-list to help me start working upgrading 1.5.x part.

Thanks,

**Comment by Alir3z4** [comment]
Well I'm running an app with
- django-nonrel-1.5-beta
- django-mongodb-engine-1.5-beta
- djangotoolbox-1.5-beta

And `nonrel-1.5-beta` branch is fine, I'm expriencing some minor issues with [mongodb-engine](https://github.com/django-nonrel/mongodb-engine/issues/165) and [djangotoolbox](https://github.com/django-nonrel/djangotoolbox/pull/40) which is not related to `nonrel-1.5-beta` branch, also I've issued a pull-request for djangotoolbox to fix it's problem.

Anyway everything else seems working fine.

**Comment by aburgel** [comment]
The 1.5 branches are still a work in progress. But I'm happy to hear that you've been able to run it successfully. I saw your pull request on djangotoolbox, I'll merge that in soon.

The best thing to do is to migrate all your code and then run your test suite. I've been doing that with my app and have come across a few issues that I was able to fix pretty easily.

Going to close this issue, feel free to reopen or create a new one if you run into more trouble.
