### ISSUE TITLE
Default site problem

### ISSUE THREAD

**Issue by fdelavega** [django-nonrel/django#4]
I just updated my django nonrel to version 1.4.  and I am using MongoDB as database. When I run a syncdb in a new database (No problem if I use my previous database) or when I run the tests it fails as if I didn't configure the SITE_ID in settings. The problem is that, when I perform this actions, django tries to create the default site using 1 as pk. as can be seen in the following code included in the file  lib/python2.7/site-packages/django/contrib/sites/management.py

<pre>
def create_default_site(app, created_models, verbosity, db, **kwargs):
     # Only create the default sites in databases where Django created the table
     if Site in created_models and router.allow_syncdb(db, Site) :
         # The default settings set SITE_ID = 1, and some tests in Django's test
         # suite rely on this value. However, if database sequences are reused
         # (e.g. in the test suite after flush/syncdb), it isn't guaranteed that
         # the next id will be 1, so we coerce it. See #15573 and #16353. This
         # can also crop up outside of tests - see #15346.
         if verbosity >= 2:
             print "Creating example.com Site object"
         Site(pk=1, domain="example.com", name="example.com").save(using=db)
         
         # We set an explicit pk instead of relying on auto-incrementation,
         # so we need to reset the database sequence. See #17415.
         sequence_sql = connections[db].ops.sequence_reset_sql(no_style(), [Site])
         if sequence_sql: 
             if verbosity >= 2:
                 print "Resetting sequence"
             cursor = connections[db].cursor()
             for command in sequence_sql:
                 cursor.execute(command)
     
     Site.objects.clear_cache()
</pre>

I fixed it in my version just changing the pk of the default site, but I think this could be a problem

**Comment by aburgel** [comment]
Not sure what the issue is here. Whats wrong with creating a default site with pk=1?

**Comment by georgedorn** [comment]
1 is not a valid primary key in mongodb.

Is there a chance you installed something that "upgraded" django-nonrel to
django?  That's happened to me before.

**Comment by aburgel** [comment]
I see. I don't think we changed anything specific, but I also don't think we've made any changes to the sites module. If you set SITE_ID to something that is legal in mongodb, does that fix the problem? Maybe the fix is to add a default value to the default mongodb settings.py

**Comment by fdelavega** [comment]
There is not a problem in the syncdb, since if the site is manually created and the id of the site is set in the SITE_ID field it works. My problem is with the testing, since, when it creates the test database it tries to create the default site using 1 as pk. I cannot fix that using fixtures because they are loaded after this problem occurs.

Note that I have fixed the problem just changing /django/contrib/sites/management.py, including a valid pk for MongoDB for the default site. However this is not a good solution since now my django only can work with MongoDB.

**Comment by aburgel** [comment]
Instead of hardcoding the pk, you can change it to use the SITE_ID setting and then set that to a valid mongodb id. That will ensure that your django is not entirely dependent on mongodb.

Just so you're aware, there are a few places in django.contrib that are not compatible with mongodb because of primary key issues like this. We've fixed many of the issues in contrib.auth because its so heavily used but not in the others.

**Comment by Alir3z4** [comment]
Hey,

You don't need to patch django at all for this. creation of default site happens on `syncdb` when you want to run tests. even when you do normal `syncdb`.

This is what I do normally in `settings.py`;

```
# Hack to ignore `site` instance creation
# This will prevent site creation on syncdb
from django.db.models import signals
from django.contrib.sites.management import create_default_site
from django.contrib.sites import models as site_app

signals.post_syncdb.disconnect(create_default_site, site_app)
```

just disconnect the `create_default_site` receiver from `post_syncdb` signal.
of course when `DEBUG=True`

This gonna solve the problem for sure ;)

**Comment by fdelavega** [comment]
Thanks! very useful.
